/*
 * Copyright (c) 2010 Yahoo! Inc. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *              http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the
 * License. See accompanying LICENSE file. 
 */
package io.s4.zeno.util;

// TODO: Auto-generated Javadoc
/**
 * The Class ZenoError.
 */
public class ZenoError extends Error {

    /**
     * Needed for serializable. Auto-generated by Eclipse.
     */
    private static final long serialVersionUID = 66977463295004680L;

    /**
     * Instantiates a new zeno error.
     * 
     * @param message
     *            the message
     * @param cause
     *            the cause
     */
    public ZenoError(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * Instantiates a new zeno error.
     * 
     * @param cause
     *            the cause
     */
    public ZenoError(Throwable cause) {
        super(cause);
    }

    /**
     * Instantiates a new zeno error.
     * 
     * @param message
     *            the message
     */
    public ZenoError(String message) {
        super(message);
    }

    /**
     * Instantiates a new zeno error.
     */
    public ZenoError() {
        super();
    }
}
